version: '2'
services: 
  discovery-service:
    build: 
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - "discovery-service"
  driver-service:
    build: 
      context: ./driverservice
      dockerfile: Dockerfile
    ports:
      - 8081:8081     
    depends_on:
      - "discovery-service"
  customer-service:
    build: 
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082 
    depends_on:
      - "discovery-service"